apiVersion: v1
kind: Service
metadata:
  name: mlops-assignment-service
spec:
  selector:
    app: mlops-assignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # Use ClusterIP; we will expose the app using an ALB Ingress
  type: ClusterIP
